name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: |
          if [ ! -f package-lock.json ]; then
            npm install
          fi
          npm ci
      - run: npm run aiken:build
      - run: npm test
      - run: npm run build
